version: "3"

services:
  backend:
    build:
      context: ./Knowledge-Base-Backend-main
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./Knowledge-Base-Frontend-main
      dockerfile: Dockerfile
    ports:
      - 4000:4000
